version: '3'

services:
  tpmongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: dummyuser
      MONGO_INITDB_ROOT_PASSWORD: 1234
    volumes:
      - mongo:/data
    ports:
      - "27017:27017"
  tpkeycloak:
    image: keycloak/keycloak:23.0
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8081:8080"
    command:
      - start-dev
      - --spi-theme-static-max-age=-1
      - --spi-theme-cache-themes=false
      - --spi-theme-cache-templates=false
      - --import-realm
    volumes:
      - ./keycloak/themes/trading-platform:/opt/keycloak/themes/trading-platform
      - ./keycloak/tp-dev-realm.json:/opt/keycloak/data/import/realm.json
  tpbackend:
    depends_on:
      - tpmongodb
      - tpkeycloak
    build: ./backend
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
        window: 60s
    environment:
      KC_CLIENT_ID: trading-platform-oauth-client
      KC_CLIENT_SECRET: Z5laOBtS69tapQfzy1i6eQ5EpTDxLEHh
      FRONTEND_ADDR: http://tpfrontend:3000
      KEYCLOAK_ADDR: http://tpkeycloak:8080
    ports:
      - "8080:8080"
  tpfrontend:
    depends_on:
      - tpbackend
    build: ./frontend
    ports:
      - "3000:3000"
    stdin_open: true
    command: npm start
    volumes:
      - ./frontend
      - /frontend/node_modules
volumes:
  mongo: {}
  keycloak: {}
