version: '2.4'

services:
  tpkeycloak:
    image: keycloak/keycloak:23.0
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8081:8080"
    command:
      - start-dev
      - --spi-theme-static-max-age=-1
      - --spi-theme-cache-themes=false
      - --spi-theme-cache-templates=false
      - --import-realm
    volumes:
      - ./keycloak/themes/trading-platform:/opt/keycloak/themes/trading-platform
      - ./keycloak/tp-dev-realm.json:/opt/keycloak/data/import/realm.json
  tpbackend:
    depends_on:
      - tpkeycloak
    build: ./backend
    restart: on-failure
    environment:
      KC_CLIENT_ID: trading-platform-oauth-client
      KC_CLIENT_SECRET: Z5laOBtS69tapQfzy1i6eQ5EpTDxLEHh
      FRONTEND_ADDR: http://127.0.0.1:3000
      KEYCLOAK_FE_ADDR: http://127.0.0.1:8081
      KEYCLOAK_BE_ADDR: http://tpkeycloak:8080
      BACKEND_ADDR: http://127.0.0.1:8080
    ports:
      - "8080:8080"
  tpfrontend:
    depends_on:
      - tpbackend
    build: ./frontend
    ports:
      - "3000:3000"
    stdin_open: true
    command: npm start
    volumes:
      - /frontend/node_modules
volumes:
  keycloak: {}
