spring:
  application:
    name: Trading Platform Backend
  webflux:
    base-path: /trading

keycloak:
  client:
    id: ${KC_CLIENT_ID:1234}
    secret: ${KC_CLIENT_SECRET:1234}

auth:
    success-url: ${FRONTEND_ADDR:http://localhost:3000/}
    failure-url: ${FRONTEND_ADDR:http://localhost:3000/}/autherr
    keycloak:
      frontend-addr: ${KEYCLOAK_FE_ADDR:http://localhost:8081}
      backend-addr: ${KEYCLOAK_BE_ADDR:http://localhost:8081}
      realm: trading-platform

cors:
  allowed:
    origin: ${FRONTEND_ADDR:http://localhost:3000/}

api:
  base-path: /api/v1
  public-base-path: /api/v1/pub

server-addr: ${BACKEND_ADDR:http://localhost:8080}